### ISSUE TITLE
Provide examples in the documentation for adding/removing instances from ELBs

### ISSUE THREAD

**Issue by dleavitt** [ranjib/knife-elb#1]
At least to me, it's not adequately clear - do we provide the node name (nope)? The aws url?

I'll send a pull request.

**Comment by ranjib** [comment]
have you tried --help ? Its a convention of knife-pluins (in fact anything that uses mixlib-cli) to use the banner as help text. Thats not sufficient ? If not, we can add more.

**Comment by ranjib** [comment]
@dleavitt , @Bairagi has updated the readme. is it  good enough?
