### ISSUE TITLE
Command for listing ec2 instances for an ELB

### ISSUE THREAD

**Issue by dleavitt** [ranjib/knife-elb#2]
Correct me if I'm missing it, but currently there doesn't seem to be a way to list the ec2 instances for an ELB. [fog provides this functionality](http://rubydoc.info/github/fog/fog/Fog/AWS/ELB/LoadBalancer#instances_in_service-instance_method), so it should be fairly straightforward to add to knife-elb as well. Either:
- modify `knife elb show` to return a list of instances
- add `knife elb instances` which returns a list of instances

**Comment by ranjib** [comment]
i am not using elb currently , so i cant confirm. But knife elb show used to display this information, if thats not the case  i think it will be a very good addition.

**Comment by subdigital** [comment]
I can confirm, `knife elb show` does list instances.  It's sort of buried in a lot of output, but you could easily grep for this.
